services:
  # ==========================================
  # PRODUCTION SERVICES (Profile: prod)
  # ==========================================
  
  proxy:
    container_name: proxy
    image: nginx:alpine
    restart: always
    profiles: ["prod"]
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - public_net

  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    profiles: ["prod"]
    expose:
      - "5000"
    environment:
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@database:27017/${MONGO_DB}?authSource=admin
      - FLASK_DEBUG=0
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - public_net
      - private_net

  database:
    container_name: database
    image: mongo:8.2.2
    restart: always
    profiles: ["prod"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes: 
      - mongo_prod_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - private_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: http://localhost
    container_name: frontend
    restart: always
    profiles: ["prod"]
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost
      - INTERNAL_API_URL=http://backend:5000
    depends_on:
    
      - backend
    networks:
      - public_net
      - private_net

  # ==========================================
  # DEVELOPMENT SERVICES (Profile: dev)
  # ==========================================

  backend-dev:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend-dev
    profiles: ["dev"]
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://dev:passwd@database-dev:27017/codesnippet?authSource=admin
      - FLASK_DEBUG=1 
      - FLASK_APP=app.py
    volumes:
      - ./backend:/app
    command: flask run --host=0.0.0.0 --port=5000
    depends_on:
      - database-dev
    networks:
      - dev_net

  database-dev:
    image: mongo:8.2.2
    container_name: database-dev
    profiles: ["dev"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=passwd
    ports: 
      - "27017:27017"
    volumes: 
      - mongo_dev_data:/data/db
    networks:
      - dev_net

volumes:
  mongo_prod_data:
  mongo_dev_data:

networks:
  public_net:
  private_net:
  dev_net: